// <auto-generated />
namespace DM2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ArticulosTags_Tags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArticulosTags_Tags));
        
        string IMigrationMetadata.Id
        {
            get { return "201910152357240_ArticulosTags_Tags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
