// <auto-generated />
namespace DM2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Users_Sections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Users_Sections));
        
        string IMigrationMetadata.Id
        {
            get { return "201910152352397_Users_Sections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
